// <auto-generated />
using System;
using EFDbRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDbRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231106211821_InitialInsuranceSysDB")]
    partial class InitialInsuranceSysDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EHR.Api.Dtos.Claim", b =>
                {
                    b.Property<string>("ClaimID")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NationalID")
                        .HasColumnType("int");

                    b.HasKey("ClaimID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EHR.Api.Dtos.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("ClaimID")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("Date");

                    b.Property<string>("ExpenseDescription")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("EHR.Api.Dtos.PolicyHolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PolicyHolders");
                });

            modelBuilder.Entity("EHR.Api.Dtos.Expense", b =>
                {
                    b.HasOne("EHR.Api.Dtos.Claim", "Claim")
                        .WithMany("Expenses")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EHR.Api.Dtos.Claim", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
